steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/loan-webhook:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'loan-webhook'
      - '--image'
      - 'gcr.io/$PROJECT_ID/loan-webhook:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/loan-webhook:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
