steps
  - name 'gcr.iocloud-buildersdocker'
    args ['build', '-t', 'gcr.io$PROJECT_IDloan-webhook$COMMIT_SHA', '.']
  - name 'gcr.iocloud-buildersgcloud'
    args
      - 'run'
      - 'deploy'
      - 'loan-webhook'
      - '--image'
      - 'gcr.io$PROJECT_IDloan-webhook$COMMIT_SHA'
      - '--region=asia-south1'
      - '--allow-unauthenticated'

images
  - 'gcr.io$PROJECT_IDloan-webhook$COMMIT_SHA'
